apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /NFS
    server: 192.168.1.17
  persistentVolumeReclaimPolicy: Retain
  storageClassName: js